name: ci-Prod-frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Enviar notificacion de comienzo de build de imagen de Docker
        uses: act10ns/slack@v2
        with: 
          status: starting
          channel: '#ci-alerts'
          message: Se comienza a construir la imagen de Docker para Produccion
        if: always()
      
      - name: Build and push - frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: serret18/web-frontend-production:${{ github.sha }}
          # platforms: linux/amd64,linux/arm64
      
      - name: send status
        uses: act10ns/slack@v2
        with: 
          channel: '#ci-alerts'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
      
      - name: "Git checkout"
        uses: "actions/checkout@v2"
        with:
          token: ${{ secrets.ACTIONS_SYSTEM_USER }}
          repository: BootCampDevOpsProject/GitOps
          ref: main
      
      - name: Change directory permissions
        run: chmod -R 777 $GITHUB_WORKSPACE
      
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"
      
      - name: Update Kubernetes resources - frontend
        run: |
          cd Frontend/web-frontend/overlays/production
          kustomize edit set image serret18/web-frontend-production=serret18/web-frontend-production:${{ github.sha }}
      
      - name: Commit files
        run: |
          git config --local user.email "luisenrique199717@gmail.com"
          git config --local user.name "luisserret"
          git commit -am "rolling image to tag $GITHUB_SHA"
      
      - name: Push changes
        run: |
          git push https://github.com/BootCampDevOpsProject/GitOps.git main
        env:
          ACTIONS_SYSTEM_USER: ${{ secrets.ACTIONS_SYSTEM_USER }}
      
      - name: send not final
        uses: act10ns/slack@v2
        with: 
          status: Finish
          channel: '#ci-alerts'
          message: El flujo de CI y actualización de repo GitOps para produccion finalizó con éxito
        if: success()

      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      
      - name: Enviar notificacion de comienzo de sonarqube
        uses: act10ns/slack@v2
        with: 
          status: starting
          channel: '#ci-alerts'
          message: Se comienza el Scanear codigo con SonarQube para produccion
        if: success()

      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # Add the URL of your instance to the variables of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
        
      - name: Notificacion final sonarqube
        uses: act10ns/slack@v2
        with: 
          status: Finish
          channel: '#ci-alerts'
          message: El Scaneo de codigo en produccion termino con exito.
        if: success()